### ISSUE TITLE
Seeing relayed communication despite faulty credentials

### ISSUE THREAD

**Issue by mehrvarz** [pion/turn#211]
### My environment

- Latest Chromium and Firefox
- pion/turn on Linux on Go 1.16

### What did I do?

I run two WebRTC apps on two separate devices and Pion Turn on a server out there. One client is provisioned with a faulty username for testing purposes. Both clients are behind different symmetric NAT's. When I start the two apps, I immediately see the following show up multiple times: "error when handling datagram: failed to handle Allocate-request from xx.xx.158.193:63415: no such user exists wrongname". This is showing the peer's correct public ip address. So far, so good.

Problem is that the relayed communication continues unfazed and I can use the two apps (talking to each other) just fine. While all authenticateRequests correctly fail, showing the public ip of the client with the wrong username, I noticed that TURN permissions are being added for the faulty client. But here the *private* ip (10.126.14.193:45436) of the peer is shown. It is the first time this ip shows up. It seems to be coming from the other peer (the one with the correct username and password) when it sends a CreatePermission request.

Why is the relayed connection not being stopped? Is the other peer expected to send the private IP in this situation? Is Pion supposed to accept it? If the other peer did this on purpose (I am pretty sure it does not), would this not be a way to circumvent Pion's permission system?

I tried to figure it out myself. But after looking at peerAddress.GetFrom(m) in handleCreatePermissionRequest() for a while I decided to post this report. Help. And apologies if this is something totally obscure on my part.

**Comment by Sean-Der** [comment]
Hey @mehrvarz 

Is one client properly authenticated? Both sides don't need to use TURN for communication to work. So the side with faulty username will still be able to use the TURN server. It just uses the Relay created by the other side. Check out the [WebRTC for the Curious](https://webrtcforthecurious.com/docs/03-connecting/#turn) section on TURN.

permissions are created for each IP address the remote peer publishes. The TURN Client that created the allocation then calls CreatePermission for each.  So if I create the TURN allocation each IP I get via addicecandidate or is in the SetRemoteDescription I go and create a permission for.

I will leave this open since we may have a auth issue I don't understand! But so far I don't believe everything is wrong, might be missing something though.

**Comment by mehrvarz** [comment]
When I change the username on the other client, so that both sides use a faulty one, the relayed connection does indeed fail. This comes as a bit of a surprise and I have to reflect on it a little longer. But thank you so very much for your quick response.

**Comment by Sean-Der** [comment]
Ok that is great to hear, it sounds like things are working :)

If you want to ask more questions I am in [Slack](https://pion.ly/slack) and always ready to help

**Comment by mehrvarz** [comment]
> So the side with faulty username will still be able to use the TURN server. It just uses the Relay created by the other side.

This is working out well. But multiple errors are thrown in the process of connecting the two clients. 2x "relay already allocated for 5-TUPLE" for the client that is getting authenticated:
https://github.com/pion/turn/blob/40ee5ed2f3ebf77582e41336b90be73cb90ee283/internal/server/turn.go#L43

And 7x "no such user exists" for the other client:
https://github.com/pion/turn/blob/40ee5ed2f3ebf77582e41336b90be73cb90ee283/internal/server/util.go#L112

It would be really good to avoid such errors while things are working out in the best possible way.
