### ISSUE TITLE
Packet unhandled

### ISSUE THREAD

**Issue by kundanSingh11** [pion/turn#26]
getting this error in the log "Packet unhandled in relay src "

Can any one help me why is this coming. 

its in nohup.out

**Comment by iMitaka** [comment]
Yesterday when i test got the same problem in this case:

I host the TURN server on my MacBook with this configuration:
$ export USERS='user=password'
$ export REALM=192.168.0.101 <- this is my local IP address from my router (tp-link)
$ export UDP_PORT=3500

In router setting i open a port ( ex MY_REAL_IP:9090 ) and forward in to 192.168.0.101:3500 to can connect remotely to TURN server.

My application use WebRTC for calling and i host it like the STUN server with local webpack server and forwarding from router.

The problem comes when i test using my phone on 4G mobile internet and my MacBook behind router wireless connection. When i make a offer from my phone to my laptop everything works fine, but when i send offer from laptop to phone the server start logging "Packet unhandled in relay src 192.168.0.101 {SOME_PORT}"

For me the problem is because the TURN server is hosted on machine behind router connection. And when the phone is host is using a Static IP that can be reached from everywhere, but laptop send a offer from local 192.168.0.101 and the mobile can not reach local IP address. 

My question is, are the problem will solve when i host TURN server on the machine that use directly Static IP ? 
Because now the problem come only when machine in local network (my laptop in home wifi network) send offer to make peerConnection with  machine with static ip (my phone 4g), but when machine with static ip (my phone 4g) send offer to make peerConnection with matching in local network (my laptop in home wifi network) this WORKS fine!

**Comment by rostopira** [comment]
I've got same error on Alibaba ECS. How could I investigate cause of issue? It works fine as STUN

**Comment by gmbad** [comment]
Hello,

Same problem here. "Packet unhandled in relay src ".

Any ideas?

Tks

**Comment by Sean-Der** [comment]
Sorry for the delay everyone!

This message can happen if you a peer without an Allocation/ChannelBind is attempting to use the TURN server's relay. This should be expected if you are attempting to contact the TURN server from behind a NAT but didn't tell the other side your public IP.

I am happy to help if you can describe your setup/how you are using the TURN server! I am also available on [Slack](https://pion.ly/slack) and happy to help anytime!

thanks for using Pion
