### ISSUE TITLE
How to use pion in window server?

### ISSUE THREAD

**Issue by HanseyChan** [pion/turn#46]
How to use pion in window server?
I need to install GO ?

**Comment by songjiayang** [comment]
You can download the binary package with [link](https://github.com/pion/turn/releases/tag/1.0.3).

**Comment by plcs2eco** [comment]
I think that you have to download either one of below executable files Songjiayang says from the [link](https://github.com/pion/turn/releases/tag/1.0.3).

simple-turn-windows-386.exe
simple-turn-windows-amd64.exe

I think that these executable files were built from Go file.  So I think that I don't need to install Go though I have installed Go, just in case.

Other [link](https://github.com/pion/turn/compare/v1.4.0...master) says to set the below env parameters.   But I don't know what I have to set instead of "user", "password", "foo", "bar" and "my-server.com". 

> $env:USERS = "user=password foo=bar"
> $env:REALM = "my-server.com"
> $env:UDP_PORT = 3478

Is there more detailed information of how to use pion in windows?

**Comment by Sean-Der** [comment]
Hi @HanseyChan  

Sorry for the delay, but I have updated the documentation to explain how to use Go to build the examples. I also generate binaries for the examples if you want to quickly deploy the existing ones.

Thanks!

----

@plcs2eco To be more consistent everything is now driven via command line arguments. I have updated the client and server examples to follow the same pattern.
